/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSignupRouteImport } from './routes/_app/signup'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as AppProtectedRouteImport } from './routes/_app/_protected'
import { Route as AppDiscoverRouteRouteImport } from './routes/_app/discover/route'
import { Route as AppDiscoverIndexRouteImport } from './routes/_app/discover/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppMoviesIdRouteImport } from './routes/_app/movies/$id'
import { Route as AppDiscoverGenreIdRouteImport } from './routes/_app/discover/$genreId'
import { Route as AppProtectedWatchlistRouteImport } from './routes/_app/_protected/watchlist'
import { Route as AppProtectedProfileRouteImport } from './routes/_app/_protected/profile'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSignupRoute = AppSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProtectedRoute = AppProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDiscoverRouteRoute = AppDiscoverRouteRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDiscoverIndexRoute = AppDiscoverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDiscoverRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMoviesIdRoute = AppMoviesIdRouteImport.update({
  id: '/movies/$id',
  path: '/movies/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDiscoverGenreIdRoute = AppDiscoverGenreIdRouteImport.update({
  id: '/$genreId',
  path: '/$genreId',
  getParentRoute: () => AppDiscoverRouteRoute,
} as any)
const AppProtectedWatchlistRoute = AppProtectedWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AppProtectedRoute,
} as any)
const AppProtectedProfileRoute = AppProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/discover': typeof AppDiscoverRouteRouteWithChildren
  '/login': typeof AppLoginRoute
  '/search': typeof AppSearchRoute
  '/signup': typeof AppSignupRoute
  '/profile': typeof AppProtectedProfileRoute
  '/watchlist': typeof AppProtectedWatchlistRoute
  '/discover/$genreId': typeof AppDiscoverGenreIdRoute
  '/movies/$id': typeof AppMoviesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/discover/': typeof AppDiscoverIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/login': typeof AppLoginRoute
  '/search': typeof AppSearchRoute
  '/signup': typeof AppSignupRoute
  '/profile': typeof AppProtectedProfileRoute
  '/watchlist': typeof AppProtectedWatchlistRoute
  '/discover/$genreId': typeof AppDiscoverGenreIdRoute
  '/movies/$id': typeof AppMoviesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/discover': typeof AppDiscoverIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/discover': typeof AppDiscoverRouteRouteWithChildren
  '/_app/_protected': typeof AppProtectedRouteWithChildren
  '/_app/login': typeof AppLoginRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/signup': typeof AppSignupRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_protected/profile': typeof AppProtectedProfileRoute
  '/_app/_protected/watchlist': typeof AppProtectedWatchlistRoute
  '/_app/discover/$genreId': typeof AppDiscoverGenreIdRoute
  '/_app/movies/$id': typeof AppMoviesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/discover/': typeof AppDiscoverIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/login'
    | '/search'
    | '/signup'
    | '/profile'
    | '/watchlist'
    | '/discover/$genreId'
    | '/movies/$id'
    | '/api/auth/$'
    | '/discover/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/search'
    | '/signup'
    | '/profile'
    | '/watchlist'
    | '/discover/$genreId'
    | '/movies/$id'
    | '/api/auth/$'
    | '/discover'
  id:
    | '__root__'
    | '/_app'
    | '/_app/discover'
    | '/_app/_protected'
    | '/_app/login'
    | '/_app/search'
    | '/_app/signup'
    | '/_app/'
    | '/_app/_protected/profile'
    | '/_app/_protected/watchlist'
    | '/_app/discover/$genreId'
    | '/_app/movies/$id'
    | '/api/auth/$'
    | '/_app/discover/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/signup': {
      id: '/_app/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AppSignupRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_protected': {
      id: '/_app/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppProtectedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/discover/': {
      id: '/_app/discover/'
      path: '/'
      fullPath: '/discover/'
      preLoaderRoute: typeof AppDiscoverIndexRouteImport
      parentRoute: typeof AppDiscoverRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/movies/$id': {
      id: '/_app/movies/$id'
      path: '/movies/$id'
      fullPath: '/movies/$id'
      preLoaderRoute: typeof AppMoviesIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/discover/$genreId': {
      id: '/_app/discover/$genreId'
      path: '/$genreId'
      fullPath: '/discover/$genreId'
      preLoaderRoute: typeof AppDiscoverGenreIdRouteImport
      parentRoute: typeof AppDiscoverRouteRoute
    }
    '/_app/_protected/watchlist': {
      id: '/_app/_protected/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AppProtectedWatchlistRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/_app/_protected/profile': {
      id: '/_app/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProtectedProfileRouteImport
      parentRoute: typeof AppProtectedRoute
    }
  }
}

interface AppDiscoverRouteRouteChildren {
  AppDiscoverGenreIdRoute: typeof AppDiscoverGenreIdRoute
  AppDiscoverIndexRoute: typeof AppDiscoverIndexRoute
}

const AppDiscoverRouteRouteChildren: AppDiscoverRouteRouteChildren = {
  AppDiscoverGenreIdRoute: AppDiscoverGenreIdRoute,
  AppDiscoverIndexRoute: AppDiscoverIndexRoute,
}

const AppDiscoverRouteRouteWithChildren =
  AppDiscoverRouteRoute._addFileChildren(AppDiscoverRouteRouteChildren)

interface AppProtectedRouteChildren {
  AppProtectedProfileRoute: typeof AppProtectedProfileRoute
  AppProtectedWatchlistRoute: typeof AppProtectedWatchlistRoute
}

const AppProtectedRouteChildren: AppProtectedRouteChildren = {
  AppProtectedProfileRoute: AppProtectedProfileRoute,
  AppProtectedWatchlistRoute: AppProtectedWatchlistRoute,
}

const AppProtectedRouteWithChildren = AppProtectedRoute._addFileChildren(
  AppProtectedRouteChildren,
)

interface AppRouteRouteChildren {
  AppDiscoverRouteRoute: typeof AppDiscoverRouteRouteWithChildren
  AppProtectedRoute: typeof AppProtectedRouteWithChildren
  AppLoginRoute: typeof AppLoginRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSignupRoute: typeof AppSignupRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMoviesIdRoute: typeof AppMoviesIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDiscoverRouteRoute: AppDiscoverRouteRouteWithChildren,
  AppProtectedRoute: AppProtectedRouteWithChildren,
  AppLoginRoute: AppLoginRoute,
  AppSearchRoute: AppSearchRoute,
  AppSignupRoute: AppSignupRoute,
  AppIndexRoute: AppIndexRoute,
  AppMoviesIdRoute: AppMoviesIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
